name: Docker container
on: repository_dispatch

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # run steps inside docker container instead of VM
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release