name: Running container in individual step
# on: push
on: repository_dispatch

# both step container and job container will be in the same docker network

jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      # This step will run in job container
      - name: Log node version
        run: node -v
      # This step will run in step container
      - name: Step with docker
      # this is how to specify docker container, similar to specifying action
      # uses: docker://<name>:<tag/version>
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version
      # This step will run in step container
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: -v
