# encrypt file on localhost
# gpg --symmetric --cipher-algo AES256 secret.json
name: Decrypt file

on: [ push ]

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/decrypted_secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print contents only TEST
        run: cat $HOME/secret.json