name: Filtering Events Workflow

on:
  push: # vsetky tieto push properties (branch, paths, tags) maju medzi sebou akoby operator AND
    branches:
      - master # it will run only when pushed to master branch
      - 'feature/*' # will match any branch with feature/ like e.g. feature/featA (!!! feature/feat/a doesnt match)
      - 'feature/**' # will match any branch with feature/ like e.g. feature/featA and also feature/feat/a
      - '!feature/featC' # this branch will be ignored
    tags:
      - v1.*
    # paths znamena ze LEN AK commit obsahuje dany file s danou priponou/cestou cize ak bol pridany, zmeneny inac sa nespusti NIC 
    # paths:
    #   - '**.js' # only when you push JS file?
    paths-ignore: # bud paths alebo paths-ignore moze byt specifikovane, v tomto pripade paths-ignore znamena ze sa workflow spusti vzdy
                  # okrem pripadu ked commit bude obsahovat docs ale len docs; ak bude aj ine subory aj docs tak sa to pusti
      - 'docs/**'
  pull_request:
    branches:
      - master # when merging to master

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -la