name: Run script plus slack message
on: push

# cize sprava sa to tak ze checkout sa robi na host/runner VM a volume mountne sa to do job aj step containerov cize subory su vzdy pristupne v containeri

jobs: 
  own-script:
    runs-on: ubuntu-latest
    container:
      # job container je spusteny s --workdir /__w/gha/gha a volume mount -v "/home/runner/work":"/__w"
      image: node:10.18.0-jessie
    steps:
      # checkout urobi checkout repa v host VM v ceste /home/runner/work/gha/gha a ta je vlastne mountnuta v job containery
      - uses: actions/checkout@v1
        name: Checkout repo 
      - name: Print workdir 
        # pwd je /__w/gha/gha
        # hack needed (chmod +x)
        run: | 
          pwd
          ls -la
          chmod +x script.sh
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: Some string
      # - name: Send a slack message
      #   uses: docker://technosophos/slack-notify
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "Hello slack"