name: Run script plus slack message
on: push

jobs: 
  own-script:
    runs-on: ubuntu-latest
    container:
      # container je spusteny s --workdir /__w/gha/gha a volume mount -v "/home/runner/work":"/__w"
      image: node:10.18.0-jessie
    steps:
      # checkout urobi checkout repa v host VM v ceste /home/runner/work/gha/gha a ta je vlastne mountnuta v job containery
      - uses: actions/checkout@v1
      - name: workdir 
        # pwd je /__w/gha/gha
        run: | 
          pwd
          ls -la
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          # entrypoint: ./script.sh
          entrypoint: ls
          # args: Some string
          args: -la
      # - name: Send a slack message
      #   uses: docker://technosophos/slack-notify
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "Hello slack"