name: Shell Commands

# on: [push]
on: repository_dispatch

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo 'Hello world'
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: pyhton cmds
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] # needs makes this job depend on another job, so this job is exec after that needed job is done first, makes execution to be in series
    steps:
      - name: Directory PowerShell
        run: Get-Location # powershell command to show cwd
      - name: Directory Bash
        run: pwd
        shell: bash
